/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Love_Light } from "next/font/google";
import "./globals.css";
// import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "@/components/ui/sonner"
import { SWRConfig } from "swr";
import { chaptersDummy, SessionDataDummy, slidesDummy, userDummy } from "@/utils/constant";
import AlertDialogIntercept from "@/components/AlertDialogIntercept";
import { Suspense } from "react";
import Loader from "@/components/Loader";

const loveLight = Love_Light({
  variable: "--font-love-light",
  subsets: ["latin"],
  weight: "400",
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // <ViewTransitions>
      <SWRConfig
        value={{
          fallback: {
            "/api/v1/me": userDummy,
            "api/v1/stories/chapters": chaptersDummy,
            // "/stories/chapters/018e3a2d-9b1e-7b1e-8b1e-1b1e1b1e1b1e/content": slidesDummy,
            "/stories/chapters/018e3a2d-9b1e-7b1e-8b1e-1b1e1b1e1b1e/session": SessionDataDummy
          },
          revalidateOnMount: true,
          revalidateOnFocus: false
        }}
        >
        <html lang="en">
          <body
            className={`font-ibm-plex-serif antialiased`}
          >
            <Toaster position="top-center"/>
            <Suspense fallback={<Loader/>}>
               <AlertDialogIntercept />
            </Suspense>
            {children}
          </body>
        </html>
      </SWRConfig>
    // </ViewTransitions>
  );
}
